# Generated by Django 4.2.6 on 2023-11-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_item"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="Items",
        ),
    ]
