# Generated by Django 4.2.6 on 2023-11-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_categories_items_item_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bids",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("bid_time", models.DateTimeField(auto_now_add=True)),
                (
                    "bid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bid_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_bids",
                        to="auctions.items",
                    ),
                ),
            ],
        ),
    ]
