# Generated by Django 4.2.6 on 2023-11-17 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="initialPrice",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watched_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watched_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auctions.items"
                    ),
                ),
            ],
        ),
    ]
